config/routes.rb
require 'sidekiq/web'

DnaBrasil::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  authenticate :user, lambda { |u| u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # CLIENT PROCESSES
  get '/clientes/:client_id/processes'            => 'clients_processes#index', as: :client_processes
  get '/clientes/:client_id/processes/novo'       => 'clients_processes#new', as: :new_client_process
  post '/clientes/:client_id/processes'           => 'clients_processes#create'  , as: :client_process
  delete '/clientes/:client_id/processes/:id'     => 'clients_processes#destroy', as: :destroy_client_processes
  get '/clientes/:client_id/processes/:id/editar' => 'clients_processes#edit', as: :edit_client_processes
  put '/clientes/:client_id/processes/:id'        => 'clients_processes#update', as: :update_client_process

  # CLIENT
  get '/clientes' => 'clients#index', as: :clients
  get '/cliente/novo' => 'clients#new', as: :new_client

  delete '/cliente/:id/remove-arquivo/:file_id' => 'clients#destroy_file', as: :destroy_file_client

  get '/cliente/:id/editar' => 'clients#edit', as: :edit_client

  post '/clientes' => 'clients#create'
  get '/clients/filtros' => 'clients#filter', as: :filter_clients
  put '/cliente/:id' => 'clients#update', as: :client
  delete '/cliente/:id' => 'clients#destroy'

  # REPORTS
  get '/relatorios' => 'reports#index', as: :reports
  get '/relatorios/filtros' => 'reports#filter', as: :filter_reports

  # USERS
  get   '/usuarios'                   => 'users#index',   as: :users
  get   '/usuario/:id'                => 'users#edit',    as: :edit_user
  get   '/usuario/reset_password/:id' => 'users#reset',   as: :reset_user
  post  '/usuarios'                   => 'users#create',  as: :user
  put   '/usuarios/:id'               => 'users#update',  as: :user
  get   '/usuario/:id/lock'           => 'users#lock',    as: :lock_user
  get   '/usuario/:id/unlock'         => 'users#unlock',  as: :unlock_user

  # USER CONFIG
  get '/configuracao/:id' => 'users#configuration', as: :config_user
  put '/configuracao/:id' => 'users#configuration_update'

  # SAC
  get  '/atendimento/cliente/:id' => 'sac#show'  , as: :sac
  post '/atendimento/cliente/:id' => 'sac#create', as: :sacs

  # GROW
  get '/grow' => 'grow#index'
  get '/grow/:notification_id' => 'grow#show'

  # DOCUMENTS
  get '/documentos/:client_id/servicos' => 'documents#index', as: :service_authorizations
  get '/documentos/:client_id/servico/novo' => 'documents#new', as: :new_service_authorization
  get '/documentos/:client_id/servico/:id' => 'documents#show', as: :service_authorization
  post '/documentos/:client_id/servico' => 'documents#create', as: :service_documents
  delete '/documentos/:client_id/remover/:id' => 'documents#destroy', as: :remove_service_authorization

  # CEP
  get '/servicos/cep/:cep' => 'custom_services#cep'

# PROXY DOCUMENT
  get '/documents/:client_id/servico/:id/procuracao' => 'proxy#show', as: :proxy_document

  # CONTRACT
  get '/documentos/:client_id/servico/:document_id/contrato'      => 'contracts#show',    as: :contract
  get '/documents/:client_id/servico/:document_id/contrato/novo'  => 'contracts#new',     as: :new_contract
  post '/documentos/:client_id/servico/:document_id/contrato'     => 'contracts#create',  as: :contracts

  # INPI
  get '/colidencias' => 'conflicts#index', as: :conflicts
  get '/colidencias/:file_id/registros' => 'conflicts#show', as: :conflict
  get '/colidencias/:file_id/registros/:id' => 'conflicts#entry', as: :entry
  post '/colidencias/' => 'conflicts#create', as: :send_conflict_file

  # AWARE DOCUMENT
  get '/documentos/:client_id/ciencia' => 'awares#show', as: :aware

  # CLIENT IMAGES
  delete '/client_images/:client_id/remover/:id' => 'clients_images#destroy', as: :remove_client_image

  root :to => 'clients#index'
end

app/models/sac.rb
class Sac
  include Mongoid::Document
  include Mongoid::Timestamps
  include EnumerateIt

  field :status
  field :call_back_at, type: DateTime

  belongs_to :user

  has_enumeration_for :status, :with => SacStatus
  embeds_many :historics, order: [:created_at, -1]
  embedded_in :client
end

app/controllers/sac_controller.rb
class SacController < ApplicationController

  before_filter :load_client
  before_filter :lock_user, only: :show

  def show
  end

  def create
    @manager = SacManager.new @client, params[:sac_entry]
    @manager.save ? unlock_and_redirect : render_error
  end

  private

  def load_client
    @client    = Client.find(params[:id])
    @documents = @client.service_documents
  end

  def lock_user
    current_user.lock(@client) if referer_is_not_show_path and current_user.lockable?
  end

  # Verifica se a URL é diferente do atendimento do cliente,
  # baseado no slug ou ID (o ID aparece na URL quando o operador já está
  # bloqueado)
  def referer_is_not_show_path
    request.referer != sac_url(@client) && request.referer != sac_url(@client.id)
  end

  def unlock_and_redirect
    current_user.unlock
    redirect_to sac_path(@client), notice: "Atendimento registrado com sucesso!"
  end

  def render_error
    flash[:error] = "Houve algum problema. Verifique os campos."
    render :show
  end
end

app/views/sac/tabs/_auth.html.erb
<%= content_for :auth do %>
  <% if @client.new_record? %>
    <%= render partial: '/sac/need_save_client', locals: {client: @client} %>
  <% elsif current_user.role != 'admin' && current_user.role != 'consultant' %>
    <%= render partial: '/sac/tabs/need_to_be_admin' %>
  <% else %>
    <section id='clients'>
      <section class='resources-btns'>
        <%= link_to 'Nova Autorização de Serviço', new_service_authorization_path(@client), class: 'button large' %>
      </section>

      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Nº</th>
            <th>Razão Social</th>
            <th>Marca</th>
            <th class='documents'>Outros documentos</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <%= render(partial: '/documents/documents', collection: @documents, as: :document) || render(partial: '/sac/tabs/no-data', locals: {collspan: 5}) %>
        </tbody>
      </table>
</section>
  <% end -%>
<% end -%>

app/views/sac/tabs/_documents.html.erb
<%= content_for :documents do %>
  <% if @client.new_record? %>
    <%= render partial: '/sac/need_save_client', locals: {client: @client} %>
  <% else %>

    <% @client.client_files.build %>

    <section class='resources-btns'>
      <%= form_for(@client, :html => {multipart: true, class: :files}) do |f| %>
        <%= f.fields_for :client_files do |file| %>
          <%= file.file_field(:file, multiple: true) if file.object.new_record? %>
        <% end -%>

        <%= f.submit "Enviar Arquivo", :disable_with => 'Enviando...' %>
      <% end %>
    </section>


    <table class='resource-table'>
      <thead>
        <th>Nome</th>
        <th>&nbsp;</th>
      </thead>
      <tbody>
        <%= render(partial: '/sac/tabs/file', collection: @client.client_files.reject{|x| x.new_record? }) || render(partial: '/sac/tabs/no-data', locals: {collspan: 4})%>
      </tbody>
    </table>
  <% end -%>
<% end -%>

app/views/sac/tabs/_file.html.erb
<tr>
  <td><%= link_to file_name(file).truncate(30), file.file.url %></td>
  <td><%= link_to 'Remover', destroy_file_client_path(@client, file), class: :remove, method: :delete, confirm: 'Você tem Certeza que deseja Remover o Arquivo?' if can?(:manager, ClientFile)%></td>
</tr>

app/views/sac/tabs/_info.html.erb
<%= content_for :info do %>
  <% if @client.new_record? %>
    <%= render partial: '/sac/need_save_client', locals: {client: @client} %>
  <% else %>
    <section class='resources-btns'>
      <%= link_to "Editar", edit_client_path(@client), class: 'button' %>
    </section>
    <div class="row-fluid">
      <div class="show_client span12">
        <section class="form">
          <section class="form-inputs">
            <%= render partial: '/sac/client_status', locals: {client: @client} %>

            <p class='title'>
              Razão Social
            </p>
            <p>
              <strong><%=m @client.company_name%></strong>
            </p>

            <p class='title'>
              Marca
            </p>
            <p>
              <strong><%= m(@client.brands.map(&:name).join(" | ")) %></strong>
            </p>

            <p class='title'>
              <%=m @client.document_type.to_sym == :company ? "CNPJ" : 'CPF' %>
            </p>

            <p>
              <strong><%= formatted_cpf(@client.cpf) || formatted_cnpj(@client.cnpj)%></strong>
            </p>

            <p class='title'>
              Nº de Processos
            </p>
            <p>
              <strong><%=m @client.client_processes.active.count%></strong>
            </p>

            <p class='title'>
              Anuidade
            </p>
            <p>
              <strong><%=m @client.translate_annuity%></strong>
            </p>

            <% @client.client_emails.each do |client_email| %>
              <p class='title'>
                E-mail
              </p>
              <p>
                <strong><%= mail_to client_email.email%></strong>
              </p>
            <%end%>

            <p class='title'>
              Nome do Contato
            </p>
            <p>
              <strong><%= @client.contact %></strong>
            </p>

            <% if @client.site.present? %>
              <p class='title'>
                Site
              </p>
              <p>
                <strong><%= link_to @client.site, "http://#{@client.site}", target: :blank %></strong>
              </p>
            <%end%>

            <section class="form-inputs">
              <p class='title'>
                Telefone 1
              </p>
              <p>
                <strong><%=m @client.primary_phone%></strong>
              </p>
            </section>

            <% if @client.secondary_phone.present? %>
              <section class="form-inputs">
                <p class='title'>
                  Telefone 2
                </p>
                <p>
                  <strong><%= @client.secondary_phone%></strong>
                </p>
              </section>
            <%end%>
          </section>
        </section>

        <section class="form right">

          <% if @client.address.present? %>
            <section class="form-inputs">
              <p class='title'>
                Endereço
              </p>
              <p>
                <strong><%= @client.address%></strong>
              </p>
            </section>
          <%end%>

          <% if @client.number.present? %>
            <section class="form-inputs">
              <p class='title'>
                Nº
              </p>
              <p>
                <strong><%= @client.number%></strong>
              </p>
            </section>
          <%end%>

          <% if @client.complement.present? %>
            <section class="form-inputs">
              <p class='title'>
                Complemento
              </p>
              <p>
                <strong><%= @client.complement%></strong>
              </p>
            </section>
          <%end%>

          <% if @client.neighborhood.present? %>
            <section class="form-inputs">
              <p class='title'>
                Bairro
              </p>
              <p>
                <strong><%= @client.neighborhood%></strong>
              </p>
            </section>
          <%end%>

          <% if @client.postal_code.present? %>
            <section class="form-inputs">
              <p class='title'>
                CEP
              </p>
              <p>
                <strong><%= @client.postal_code%></strong>
              </p>
            </section>
          <%end%>

          <% if @client.city.present? %>
            <section class="form-inputs">
              <p class='title'>
                Cidade
              </p>
              <p>
                <strong><%= @client.city%></strong>
              </p>
            </section>
          <%end%>

        <% if @client.state.present? %>    
          <section class="form-inputs">
            <p class='title'>
              Estado
            </p>
            <p>
              <strong><%= @client.state%></strong>
            </p>
          </section>
        <%end%>      
        </section>
      </div>

      <div id="show_logo" class="span12">
        <section class="form-inputs">
          <p class='title'>
            Logos
          </p>
          <ul>
            <% @client.client_images.each do |image| %>
              <li>
                <%= link_to image_tag(image.file.url, width: '134px'), image.file.url, target: "black" %>
                <div class='actions'>
                  <%= link_to "remover", remove_client_image_path(@client, image), method: :delete, confirm: 'Deseja remover esse logo?' %>
                </div>
              </li>
            <% end %>
          </ul>
        </section>
      </div>
    </div>
  <% end -%>
<% end -%>

app/views/sac/tabs/_links.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Informações', '#info'%>
    </li>
    <li>
      <%= link_to 'Processos', '#process' %>
    </li>
    <li>
      <%= link_to 'Documentos', '#documents' %>
    </li>
    <li>
      <%= link_to 'Autorização', '#auth' %>
    </li>
  </ul>
</nav>

app/views/sac/tabs/_main.html.erb
<section class='tabs'>
  <header>
    <h2 class='sprite show-client'>Clientes</h2>
    <%= render partial: 'sac/tabs/links' %>
  </header>

  <article id='info'>       <%= yield :info  %>      </article>
  <article id='documents'>  <%= yield :documents %> </article>
  <article id='process'>    <%= yield :process %>   </article>
  <article id='auth'>       <%= yield :auth %>      </article>
</section>

app/views/sac/tabs/_need_to_be_admin.html.erb
<table class='resource-table need-save-client'>
  <thead>
    <th>&nbsp;</th>
  </thead>
  <tbody>
    <tr>
      <td> Somente Administradores podem acessar esta área. </td>
    </tr>
  </tbody>
</table>

app/views/sac/tabs/_no-data.html.erb
<tr>
  <td colspan='<%= defined?(collspan) ? collspan : 2 %>'>Nenhum dado encontrado</td>
</tr>

app/views/sac/tabs/_process.html.erb
<%= content_for :process do %>
  <% if @client.new_record? %>
    <%= render partial: '/sac/need_save_client', locals: {client: @client} %>
  <% else %>
    <section class='resources-btns client process'>
      <%= link_to 'Novo Processo', new_client_process_path(@client), class: 'button large' %>
    </section>

    <table class='table table-bordered table-striped'>
      <thead>
        <tr>
          <th>Nº do Processo</th>
          <th>Depósito em</th>
          <th>Concessão em</th>
          <th>Vigência até</th>
          <th>Inicio Prazo Ordinário</th>
          <th>Fim Prazo Ordinário</th>
          <th>Inicio Prazo Extraordinário</th>
          <th>Fim Prazo Extraordinário</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: '/sac/tabs/processess_info', collection: @client.client_processes.active) || render(partial: '/sac/tabs/no-data', locals: {collspan: 9})%>
      </tbody>
    </table>
  <% end -%>
<% end -%>

app/views/sac/tabs/_processess_info.html.erb
<tr>
  <td><%= processess_info.number %></td>
  <td><%= l(processess_info.filing_at) if processess_info.filing_at.present? %></td>
  <td><%= l(processess_info.grant_at) if processess_info.grant_at.present? %></td>
  <td><%= l(processess_info.validity_at) if processess_info.validity_at.present? %></td>
  <td><%= l(processess_info.start_ordinary_appeal) if processess_info.start_ordinary_appeal.present? %></td>
  <td><%= l(processess_info.finish_ordinary_appeal) if processess_info.finish_ordinary_appeal.present? %></td>
  <td><%= l(processess_info.start_extraordinary_appeal) if processess_info.start_extraordinary_appeal.present? %></td>
  <td><%= l(processess_info.finish_extraordinary_appeal) if processess_info.finish_extraordinary_appeal.present? %></td>
  <td>
    <%= link_to "Editar", edit_client_processes_path(processess_info.client, processess_info) %>
    <%= link_to "Remover", destroy_client_processes_path(processess_info.client, processess_info), method: :delete, confirm: 'Você tem certeza que deseja remover?' %>
  </td>
</tr>