config/routes.rb
require 'sidekiq/web'

DnaBrasil::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  authenticate :user, lambda { |u| u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # CLIENT PROCESSES
  get '/clientes/:client_id/processes'            => 'clients_processes#index', as: :client_processes
  get '/clientes/:client_id/processes/novo'       => 'clients_processes#new', as: :new_client_process
  post '/clientes/:client_id/processes'           => 'clients_processes#create'  , as: :client_process
  delete '/clientes/:client_id/processes/:id'     => 'clients_processes#destroy', as: :destroy_client_processes
  get '/clientes/:client_id/processes/:id/editar' => 'clients_processes#edit', as: :edit_client_processes
  put '/clientes/:client_id/processes/:id'        => 'clients_processes#update', as: :update_client_process

  # CLIENT
  get '/clientes' => 'clients#index', as: :clients
  get '/cliente/novo' => 'clients#new', as: :new_client

  delete '/cliente/:id/remove-arquivo/:file_id' => 'clients#destroy_file', as: :destroy_file_client

  get '/cliente/:id/editar' => 'clients#edit', as: :edit_client

  post '/clientes' => 'clients#create'
  get '/clients/filtros' => 'clients#filter', as: :filter_clients
  put '/cliente/:id' => 'clients#update', as: :client
  delete '/cliente/:id' => 'clients#destroy'

  # REPORTS
  get '/relatorios' => 'reports#index', as: :reports
  get '/relatorios/filtros' => 'reports#filter', as: :filter_reports

  # USERS
  get   '/usuarios'                   => 'users#index',   as: :users
  get   '/usuario/:id'                => 'users#edit',    as: :edit_user
  get   '/usuario/reset_password/:id' => 'users#reset',   as: :reset_user
  post  '/usuarios'                   => 'users#create',  as: :user
  put   '/usuarios/:id'               => 'users#update',  as: :user
  get   '/usuario/:id/lock'           => 'users#lock',    as: :lock_user
  get   '/usuario/:id/unlock'         => 'users#unlock',  as: :unlock_user

  # USER CONFIG
  get '/configuracao/:id' => 'users#configuration', as: :config_user
  put '/configuracao/:id' => 'users#configuration_update'

  # SAC
  get  '/atendimento/cliente/:id' => 'sac#show'  , as: :sac
  post '/atendimento/cliente/:id' => 'sac#create', as: :sacs

  # GROW
  get '/grow' => 'grow#index'
  get '/grow/:notification_id' => 'grow#show'

  # DOCUMENTS
  get '/documentos/:client_id/servicos' => 'documents#index', as: :service_authorizations
  get '/documentos/:client_id/servico/novo' => 'documents#new', as: :new_service_authorization
  get '/documentos/:client_id/servico/:id' => 'documents#show', as: :service_authorization
  post '/documentos/:client_id/servico' => 'documents#create', as: :service_documents
  delete '/documentos/:client_id/remover/:id' => 'documents#destroy', as: :remove_service_authorization

  # CEP
  get '/servicos/cep/:cep' => 'custom_services#cep'

# PROXY DOCUMENT
  get '/documents/:client_id/servico/:id/procuracao' => 'proxy#show', as: :proxy_document

  # CONTRACT
  get '/documentos/:client_id/servico/:document_id/contrato'      => 'contracts#show',    as: :contract
  get '/documents/:client_id/servico/:document_id/contrato/novo'  => 'contracts#new',     as: :new_contract
  post '/documentos/:client_id/servico/:document_id/contrato'     => 'contracts#create',  as: :contracts

  # INPI
  get '/colidencias' => 'conflicts#index', as: :conflicts
  get '/colidencias/:file_id/registros' => 'conflicts#show', as: :conflict
  get '/colidencias/:file_id/registros/:id' => 'conflicts#entry', as: :entry
  post '/colidencias/' => 'conflicts#create', as: :send_conflict_file

  # AWARE DOCUMENT
  get '/documentos/:client_id/ciencia' => 'awares#show', as: :aware

  # CLIENT IMAGES
  delete '/client_images/:client_id/remover/:id' => 'clients_images#destroy', as: :remove_client_image

  root :to => 'clients#index'
end

app/controllers/documents_controller.rb
# encoding: UTF-8
class DocumentsController < ApplicationController
  authorize_resource :service_document
  before_filter :load_client

  def index
    @documents = @client.service_documents
  end

  def show
    @document = @client.service_documents.find(params[:id])
    send_data Generator::Authorization::Base.new(@document).generate,
              type:        "application/pdf",
              filename:    "Autorização.pdf",
              disposition: "inline"
  end

  def new
    last = ServiceDocument.where(client_id: @client.id).last
    if last
      @document = ServiceDocument.new(
        person_name: last.person_name,
        nationality: last.nationality,
        relationship_status: last.relationship_status,
        rg: last.rg,
        cpf: last.cpf,
        birth_date: last.birth_date,
        occupation: last.occupation,
        position: last.position
      )
    else
      @document = ServiceDocument.new
    end  
  end

  def create
    manager   = ServiceDocumentManager.new(@client, params[:service_document])
    @document = manager.document

    if manager.save
      TrackerDocument.register(@client, current_user, "ServiceDocument", "create")
      redirect_to service_authorizations_path(@client, anchor: :auth), :notice => "Autorização de serviço criada com sucesso."
    else
      render "new"
    end
  end

  def edit
    
  end

  def destroy
    @document = @client.service_documents.find(params[:id])
    @document.destroy

    redirect_to service_authorizations_path(@client), :notice => "Autorização de serviço removida com sucesso."
  end

  private

  def load_client
    @client = Client.find(params[:client_id])

    @sac = Sac.new
    @sac.historics.build
  end
end

app/views/documents/_documents.html.erb
<tr>
  <td><%= link_to("%05d" % document.number, service_authorization_path(document.client, document), target: "_blank") %></td>
  <td><%= m document.client.company_name%></td>
  <td><%= m(@client.brands.map(&:name).join(" | ")) %></td>
  <td>
    <% if document.contract %>
      <%= link_to "Ver Contrato", contract_path(document.client, document), target: :blank, class: "btn" %>
    <% else %>
      <%= link_to "Gerar Contrato", new_contract_path(document.client, document), class: "btn" %>
    <% end %>
    <%= link_to "Procuração", proxy_document_path(document.client, document), target: :blank, class: "btn" %>

    <%= link_to "Carta de ciência", aware_path(document.client), class: "btn", target: "_blank" %>
  </td>
  <td><%= link_to '[ X ]', remove_service_authorization_path(document.client, document), method: :delete, confirm: "Deseja remover a autorização de serviço #{document.number}" if can? :manage, ServiceDocument %>
</tr>

app/views/documents/_form.html.erb
<section class='resources-btns'>
  <%= link_to 'Autorizações de Serviço', service_authorizations_path(@client, anchor: :auth), class: 'button large' %>
</section>

<%= simple_form_for(@document, :html => {:class => 'form-horizontal authorization-form two-columns', :'data-tab-start' => '3' }) do |form| %>
  <%= render partial: 'shared/form_errors', locals: {resource: @document } %>

  <article class='first'>
    <%= form.input :amount %>
    <%= form.input :payment %>
    <%= form.input :person_name %>
    <%= form.input :nationality %>
    <%= form.input :relationship_status, collection: ServiceDocument::RelationshipStatus.to_a, include_blank: false %>
    <%= form.input :rg %>
    <%= form.input :cpf %>
   <%= form.input :birth_date, input_html: { class: 'mask-date', value: params[:service_document].present? ? params[:service_document][:birth_date] : (form.object.birth_date && form.object.birth_date.strftime('%d/%m/%Y')) } %>
    <%= form.input :occupation %>
  </article>

  <article>
    <%= form.input :position %>
    <%= form.input :agent %>
    <%= form.input :agency %>
    <%= form.input :observations, as: :text %>
    <%= form.input :description, as: :text %>
  </article>

  <footer>
    <%= form.button :submit, "Salvar", class: 'button large' %>
  </footer>
<% end %>

app/views/documents/index.html.erb
<section class='resource client index'>
  <%= render partial: 'sac/tabs/info' %>
  <%= render partial: 'sac/tabs/documents' %>
  <%= render partial: 'sac/tabs/process' %>
  <%= render partial: 'sac/tabs/auth' %>

  <%= render partial: 'sac/tabs/main' %>

  <section class='resource_menu'>
    <section class='resource_title'>
      <h1 class='sprite sac'>Atendimento</h1>
    </section>
  </section>

  <%= render 'sac/form' unless @client.new_record?%>
</section>

app/views/documents/new.html.erb
<section class='resource client index'>

  <%= render partial: 'sac/tabs/info' %>
  <%= render partial: 'sac/tabs/documents' %>
  <%= render partial: 'sac/tabs/process' %>
  <%= content_for :auth do%>
    <%= render partial: 'form' %>
  <% end -%>

  <%= render partial: 'sac/tabs/main' %>

  <section class='resource_menu'>
    <section class='resource_title'>
      <h1 class='sprite sac'>Atendimento</h1>
    </section>
  </section>

  <%= render 'sac/form' unless @client.new_record?%>
</section>

app/views/documents/service_authorization.html.erb
<div id="document-header">
  <div class="logo">
    <%= image_tag("logo.png") %>
  </div>

  <div class="title">
    <h1>AUTORIZAÇÃO DE SERVIÇO</h1>
  </div>

  <div class="subtitle">
    <h2>ASSESSORIA DA PROPRIEDADE INDUSTRIAL</h2>
  </div>

  <div class="document_number">
    Nº <%= "%05d" % @document.number %>
  </div>
</div>

<table class="border" width="100%">
  <tr>
    <td>CLIENTE: <strong><%= @document.company_name %></strong></td>
    <td colspan="4"></td>
  </tr>

  <tr>
    <td>ENDEREÇO: <strong><%= @document.full_address %></strong></td>
    <td colspan="4"></td>
  </tr>

  <tr>
    <td>BAIRRO: <strong><%= @document.neighborhood %></strong></td>
    <td>CIDADE: <strong><%= @document.city %></strong></td>
    <td>EST: <strong><%= @document.state %></strong></td>
    <td colspan="2"></td>
  </tr>

  <tr>
    <td>CPF/CNPJ: <strong><%= formatted_cpf(@document.client_document) || formatted_cnpj(@document.client_document) %></strong></td>
    <td colspan="4"></td>
  </tr>

  <tr>
    <td>FONE: <strong><%= @document.phone %></strong></td>
    <td>CONTATO: <strong><%= @document.contact %></strong></td>
    <td>CEP: <strong><%= @document.postal_code %></strong></td>
    <td colspan="2"></td>
  </tr>
</table>

<table class="border informations" width="100%">
  <tr>
    <td>AUTORIZAMOS A <%= t('project.company_name')%>, A EXECUTAR NO(A) <%= @document.agency %> OS SERVIÇOS ABAIXO
      DISCRIMINADOS</td>
    <tr>
      <td><strong><%= @document.description %></strong></td>
    </tr>
  </tr>
</table>

<table class="border" width="100%">
  <tr>
    <td>O PRESENTE SERVIÇO IMPORTA EM R$: <strong><%= @document.amount %></strong></td>
    <td colspan="4"></td>
  </tr>

  <tr>
    <td>FORMA DE PAGAMENTO: <strong><%= @document.payment %></strong></td>
    <td colspan="4"></td>
  </tr>
</table>

<table class="border" width="100%">
  <tr>
    <th colspan="6">DADOS PARA PROCURAÇÃO</th>
  </tr>

  <tr>
    <td>NOME DO OUTORGANTE: <strong><%= @document.person_name %></strong></td>
    <td colspan="5"></td>
  </tr>

  <tr>
    <td>NACIONALIDADE: <strong><%= @document.nationality %></strong></td>
    <td>ESTADO CIVIL: <strong><%= @document.relationship_status_humanize %></strong></td>
    <td colspan="4"></td>
  </tr>

  <tr>
    <td>RG: <strong><%= @document.rg %></strong></td>
    <td>DATA NASC.: <strong><%= l(@document.birth_date) %></strong></td>
    <td>CPF: <strong><%= formatted_cpf(@document.cpf) %></strong></td>
    <td colspan="3"></td>
  </tr>

  <tr>
    <td>PROFISSÃO: <strong><%= @document.occupation %></strong></td>
    <td>CARGO: <strong><%= @document.position %></strong></td>
    <td colspan="4"></td>
  </tr>

  <tr>
    <td>OBSERVAÇÕES: <strong><%= @document.observations %></strong></td>
    <td colspan="5"></td>
  </tr>
</table>

<table class="border" width="100%">
  <tr>
    <td>AGENTE: <strong><%= @document.agent %></strong></td>
  </tr>

  <tr>
    <td>CLIENTE: <strong><%= @document.company_name %></strong></td>
  </tr>

  <tr>
    <td>LOCAL/DATA: <strong><%= "#{@document.city}, #{l(@document.created_at, format: :local)}" %></strong></td>
  </tr>

  <tr>
    <td>ASSINATURA:</td>
  </tr>

  <tr>
    <td>CARIMBO:</td>
  </tr>

  <tr>
    <td>
      <strong>LEGALIZAÇÃO EM GERAL:</strong>
      E por estarem justos e contratados, firmam o presente em 02 (duas) vias,
      selando desta forma os compromissos acima especificados, nas condições
      tratadas e aceitas por ambas as partes, não cabendo dúvida ou
      reclamação posterior, tendo em vista os termos. Quaisquer despachos
      relativos ao pedido em referência, serão prontamente levados ao
      conhecimento da Contratante, correndo por conta e risco da mesma, quaisquer
      inobservâncias ao cumprimento dos prazos estipulados na legislação
      em vigor "Lei 9.279 de 14 de maio de 1996". Art. 49 - Lei 8.078 - O
      contratante não poderá cancelar o mesmo após sete dias da assinatura.
    </td>
  </tr>
</table>