config/routes.rb
require 'sidekiq/web'

DnaBrasil::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  authenticate :user, lambda { |u| u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # CLIENT PROCESSES
  get '/clientes/:client_id/processes'            => 'clients_processes#index', as: :client_processes
  get '/clientes/:client_id/processes/novo'       => 'clients_processes#new', as: :new_client_process
  post '/clientes/:client_id/processes'           => 'clients_processes#create'  , as: :client_process
  delete '/clientes/:client_id/processes/:id'     => 'clients_processes#destroy', as: :destroy_client_processes
  get '/clientes/:client_id/processes/:id/editar' => 'clients_processes#edit', as: :edit_client_processes
  put '/clientes/:client_id/processes/:id'        => 'clients_processes#update', as: :update_client_process

  # CLIENT
  get '/clientes' => 'clients#index', as: :clients
  get '/cliente/novo' => 'clients#new', as: :new_client

  delete '/cliente/:id/remove-arquivo/:file_id' => 'clients#destroy_file', as: :destroy_file_client

  get '/cliente/:id/editar' => 'clients#edit', as: :edit_client

  post '/clientes' => 'clients#create'
  get '/clients/filtros' => 'clients#filter', as: :filter_clients
  put '/cliente/:id' => 'clients#update', as: :client
  delete '/cliente/:id' => 'clients#destroy'

  # REPORTS
  get '/relatorios' => 'reports#index', as: :reports
  get '/relatorios/filtros' => 'reports#filter', as: :filter_reports

  # USERS
  get   '/usuarios'                   => 'users#index',   as: :users
  get   '/usuario/:id'                => 'users#edit',    as: :edit_user
  get   '/usuario/reset_password/:id' => 'users#reset',   as: :reset_user
  post  '/usuarios'                   => 'users#create',  as: :user
  put   '/usuarios/:id'               => 'users#update',  as: :user
  get   '/usuario/:id/lock'           => 'users#lock',    as: :lock_user
  get   '/usuario/:id/unlock'         => 'users#unlock',  as: :unlock_user

  # USER CONFIG
  get '/configuracao/:id' => 'users#configuration', as: :config_user
  put '/configuracao/:id' => 'users#configuration_update'

  # SAC
  get  '/atendimento/cliente/:id' => 'sac#show'  , as: :sac
  post '/atendimento/cliente/:id' => 'sac#create', as: :sacs

  # GROW
  get '/grow' => 'grow#index'
  get '/grow/:notification_id' => 'grow#show'

  # DOCUMENTS
  get '/documentos/:client_id/servicos' => 'documents#index', as: :service_authorizations
  get '/documentos/:client_id/servico/novo' => 'documents#new', as: :new_service_authorization
  get '/documentos/:client_id/servico/:id' => 'documents#show', as: :service_authorization
  post '/documentos/:client_id/servico' => 'documents#create', as: :service_documents
  delete '/documentos/:client_id/remover/:id' => 'documents#destroy', as: :remove_service_authorization

  # CEP
  get '/servicos/cep/:cep' => 'custom_services#cep'

# PROXY DOCUMENT
  get '/documents/:client_id/servico/:id/procuracao' => 'proxy#show', as: :proxy_document

  # CONTRACT
  get '/documentos/:client_id/servico/:document_id/contrato'      => 'contracts#show',    as: :contract
  get '/documents/:client_id/servico/:document_id/contrato/novo'  => 'contracts#new',     as: :new_contract
  post '/documentos/:client_id/servico/:document_id/contrato'     => 'contracts#create',  as: :contracts

  # INPI
  get '/colidencias' => 'conflicts#index', as: :conflicts
  get '/colidencias/:file_id/registros' => 'conflicts#show', as: :conflict
  get '/colidencias/:file_id/registros/:id' => 'conflicts#entry', as: :entry
  post '/colidencias/' => 'conflicts#create', as: :send_conflict_file

  # AWARE DOCUMENT
  get '/documentos/:client_id/ciencia' => 'awares#show', as: :aware

  # CLIENT IMAGES
  delete '/client_images/:client_id/remover/:id' => 'clients_images#destroy', as: :remove_client_image

  root :to => 'clients#index'
end

app/models/conflict.rb
class Conflict
  include Mongoid::Document

  field :value
  embedded_in :client
end

app/controllers/conflicts_controller.rb
#encoding: UTF-8
class ConflictsController < ApplicationController
  before_filter :load_file, only: [:show, :entry]

  def index
    @files = Inpi::File.all.order_by([:created_at, :desc])
  end

  def show
    @conflicts = @file.entries
  end

  def entry
    @entry = @file.entries.where(number: params[:id]).first
  end

  def create
    manager = InpiWorkerManager.new(params[:inpi_file_url])

    if manager.valid?
      InpiWorker.perform_async(params[:inpi_file_url])
      redirect_to conflicts_path, notice: "Arquivo adicionado com sucesso. Em instantes ele aparecerá na fila de processamento."
    else
      redirect_to conflicts_path, notice: "Arquivo inválido ou já existe."
    end
  end

  private

  def load_file
    @file = Inpi::File.find(params[:file_id])
  end
end

app/views/conflicts/_conflicts.html.erb
<tr>
  <td><%= link_to(inpi.number, entry_path(inpi.file, inpi.number)) %></td>
  <td><%= link_to(inpi.client.company_name, sac_path(inpi.client)) %></td>
  <td><%= inpi.company_name %></td>
  <td><%= inpi.brand %></td>
  <td><%= inpi.conflict %></td>
</tr>

app/views/conflicts/entry.html.erb
<section class='resource'>
  <section class='resources-btns'>
    <%= link_to "Voltar", conflict_path(@entry.file), class: 'button' %>
  </section>
</section>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nº</th>
      <th>Data</th>
      <th>Classe</th>
      <th>Razão Social</th>
      <th>Inpi</th>
      <th>Apresentação</th>
      <th>Natureza</th>
      <th>Marca</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @entry.number %></td>
      <td><%= @entry.date%></td>
      <td><%= @entry.class_name %></td>
      <td><%= @entry.company_name %></td>
      <td><%= @entry.inpi %></td>
      <td><%= @entry.presentation %></td>
      <td><%= @entry.nature %></td>
      <td><%= @entry.brand %></td>
    </tr>
  </tbody>
</table>

app/views/conflicts/index.html.erb
<section class='resource'>
  <section class='resources-btns conflict_files'>
    <%= form_tag(send_conflict_file_path) do %>
      <ul>
        <li>
          <%= label_tag 'Arquivo INPI' %>
          <%= text_field_tag :inpi_file_url, nil, class: 'large' %>
        </li>
      </ul>
      <%= submit_tag 'enviar' %>
    <% end %>
  </section>
</section>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Arquivo</th>
      <th>Data</th>
      <th>Status</th>
      <th>Quantidade de Registros</th>
      <th>Finalizado em</th>
    </tr>
  </thead>
  <tbody>
    <% @files.each do |file| %>
      <tr>
        <td><%= file.finished? ? link_to(file.name, conflict_path(file)) : file.name %></td>
        <td><%= l(file.created_at) %></td>
        <td><%= t(file.status, scope: [:state_machines, :inpi_file]) %></td>
        <td><%= file.entries.count if file.finished? %></td>
        <td><%= l(file.finished_at) if file.finished? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/conflicts/show.html.erb
<section class='resource'>
  <section class='resources-btns'>
    <%= link_to "Voltar", conflicts_path, class: 'button' %>
  </section>
</section>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Número</th>
      <th>Cliente</th>
      <th>Razão Social</th>
      <th>Marca</th>
      <th>Colidência</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'conflicts', collection: @conflicts, as: :inpi %>
  </tbody>
</table>